services:

  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mp-subscription-db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    name: mp-subscription-db


